# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: 4.0
sudo: true

env:
  - RENV_CONFIG_REPOS_OVERRIDE="https://cloud.r-project.org"

cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library
  packages: true

install:
  - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
  - Rscript -e "renv::restore()"

script:
  - ./scrnatools build
  - ./scrnatools stats

deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  local-dir: docs
  target_branch: website
  on:
    branch: master
  edge: true # opt in to dpl v2

notifications:
  email:
    on_success: change
    on_failure: change
